### PR TITLE
Added heartbeat option

### PR DESCRIPTION
**Pull request by pietdevaere**
Add a flag to let the client automatically sends messages to the server in order to load the connection

### CODE REVIEW

**Comment by pietdevaere** [comment]
I screwed up here, sorry

**Comment by ekr** [comment]
@pietdevaere: can you expand on the state here? Does this work?

**Comment by pietdevaere** [comment]
It seems to work well with a lightly loaded connection e.g. 1 heartbeat per 100ms, but when bumping up the frequency something will always break. First it was the packet size bug from PR24, then the problem with the ACKs in PR26. At the moment I'm not sure what is the problem, but I'm tracking it down.

But I think these are all issues not directly related to this PR, so yeah, I would say it works.

**Comment by pietdevaere** [comment]
This works.

**Pull request merged**
